name: GitHub Classroom Workflow
on:
  push:
    branches:
      - master
      - lab_02
  pull_request:
    branches:
      - master
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: docker/setup-buildx-action@v2

      - name: Build images
        timeout-minutes: 10
        run: |
          docker-compose build postgres
          docker-compose build api-gateway
          docker-compose build flight-service
          docker-compose build bonus-service
          docker-compose build ticket-service
          docker-compose build cancel-bonus-broker
      - name: Setup db
        run: |
          docker-compose up -d postgres
          docker-compose logs postgres
          sleep 5
          cd postgres
          chmod +x ./create-test-db.sh  && ./create-test-db.sh
          cd ..
      - name: Setup broker
        run: |
          docker-compose up -d rabbitmq
          sleep 5

      - name: Run containers
        timeout-minutes: 10
        run: |
          docker-compose up -d api-gateway
          docker-compose up -d cancel-bonus-broker

          docker-compose logs ticket-service
          docker-compose logs flight-service
          docker-compose logs bonus-service
          docker-compose logs api-gateway
          docker-compose logs cancel-bonus-broker
          chmod +x ./scripts/wait-script.sh  && ./scripts/wait-script.sh
        env:
          WAIT_PORTS: 8080,8070,8060,8050

      - name: Run API Tests
        timeout-minutes: 5
        run: ./scripts/test-script.sh v1 bonus-service 8050

      - name: Stop containers
        if: always()
        continue-on-error: true
        run: docker compose down -v